Spring-03
Max-Pochepets/booking-system pull request #3
Opened 2021-02-09 10:28 UTC by Max-Pochepets

Spring MVC

- Spring MVC configured
- UserResponseDTO created
- UserMapper created
- UserController implemented

2021-02-10 02:46 UTC, Resci approved these changes

2021-02-10 16:00 UTC, dmytro-hryhoruk requested changes

2021-02-10 16:00 UTC, dmytro-hryhoruk commented on src/main/java/com/booking/service/controller/UserController.java
> +            }
It would take less place to just create four users

2021-02-10 16:00 UTC, dmytro-hryhoruk commented on src/main/java/com/booking/service/dao/impl/UserDaoImpl.java
> +            return Optional.ofNullable(user);
let's do this inline

2021-02-10 16:00 UTC, dmytro-hryhoruk commented on src/main/java/com/booking/service/dto/UserResponseDto.java
> +    private String name;
let's add id too

2021-02-10 16:00 UTC, dmytro-hryhoruk commented on src/main/java/com/booking/service/service/UserMapper.java
> +    public User fromDto(UserResponseDto inputUserDto) {
we don't need this method for now

2021-02-10 16:00 UTC, dmytro-hryhoruk commented on src/main/java/com/booking/service/service/impl/UserServiceImpl.java
> +        return userDao.get(id).get();
is it okay to make to request to DB for one user?

2021-02-11 08:30 UTC, dmytro-hryhoruk requested changes

2021-02-11 08:30 UTC, dmytro-hryhoruk commented on src/main/java/com/booking/service/service/impl/UserServiceImpl.java
> +        return optionalUser.get();
1) you can do this check inline with optional;
2) It's better to throw an exception(you can use orElseThrow for this)

2021-02-11 09:27 UTC, dmytro-hryhoruk approved these changes

2021-02-11 09:28 UTC, merged